### ISSUE TITLE
Add ability to rate all posts, not the first one

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#1]
Add ability to rate all posts, not the first one

**Comment by WhiteNeo** [comment]
I have to think about this because maybe there are a lot of work and charge into server, that was the reason i have added only in first post, but you maybe i can add it the option i was thinked on that and for that reason i have added the code just in case. But in threadlist will only shows the first post due only that fact was recorded to betterize mod :)

**Comment by WhiteNeo** [comment]
Ok done, option was added. But have to work on it i see it that does not work due tid is the same and well i have to work on this some more time to set lists and more right, i let this open again...

**Comment by WhiteNeo** [comment]
Ok this one was added in this new version and it is working fine now :)
