### ISSUE TITLE
Display reactions on thread list

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#17]
As mentioned here #5 

it should show only emoji smileys from the first post, or add a new setting.

**Comment by WhiteNeo** [comment]
I will add a new settings for this but i think the best way is actual one, due it adds all entire contents of the thread because it is a thread so all reaction was listed there and on click you may see wich post is, and many more, and on every post own cownters are taken ;)

**Comment by WhiteNeo** [comment]
https://github.com/WhiteNeo/post_rate/issues/22#issuecomment-354378576

**Comment by WhiteNeo** [comment]
Ok this part is working select only to show first post and make a recount.

Or use all and retrieve all that is the right way to work in this mod, but you can modify this part easily due i have to add more code in this part but you can remove that code and done :)

**Comment by Eldenroot** [comment]
OK, what to change? Thank you

**Comment by WhiteNeo** [comment]
Only use in first post, or changing the entire hook into templatesets or all the code inside thread var addons.

This one all users have asked this way i have 8 petitions to do it as actually, so if there are more with the same as you have asked for maybe i add it a new option for it, but actually the only way is changing the hooks or entire code. (That is a waste of time due this works this way in new versions but you can take the old code version as reference). In that repo only first post are taken, but all users told me is a thread nos a first post, so all emojis have to be listed, and yeah it makes sense, so all emojis are there in threadlist because all emojis are in that thread :) If there is a post list then we can do that, but when you enter into thread first post and all posts have own results, so you can use the hook inside threads to use post instead thread list :)

**Comment by WhiteNeo** [comment]
Ok i have added this due your request, now you can setting it up to show all items in posts or only firstpost in threadlist, is configurable into admincp.

I hope this can help to you in your request :)

**Comment by Eldenroot** [comment]
Thank you, works fine! Really cool!
