### ISSUE TITLE
Recount feature

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#19]
When you remove the reaction or delete the thread/post with reactions added, the counter for every users is not updated. It should be added as a task in ACP which will run every 24 hours and recount everything

**Comment by WhiteNeo** [comment]
I will add this because this is the latest implementation and is green only that reason i rewrite at first the recoun task because is very important in case of missing things, but of course i will write the part of given, remove to works fine all senses and posible cases thanks this is the next one thing i will fix :)

**Comment by WhiteNeo** [comment]
Ok this is ended now rebuild task works fine and add some cryteria but the most important now i have added the right values into rates given and received for users and use ajax to make it more visual.
