### ISSUE TITLE
Add templates for easier modification

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#21]
Template group for Post rate is empty... really difficult to change hardcoded items :( would be better to add templates.

**Comment by WhiteNeo** [comment]
This will be the first listed action i got, i have templates to all plugin and converter for my thanks system, but you have asked yours too so i will add it then. But this is on the list when al posible bugs are fixed :)

**Comment by WhiteNeo** [comment]
Ok i have to let this open due mybb was not response in right values into lang vars and templates so it will be a waste of time to do something that does not response or broke all plugin functions due this.

When they give me a feedback or a response on the new way to get right values inside templates or i found a new way to do i can start with this, otherwise with the right styles i think all should be fine.

**Comment by WhiteNeo** [comment]
Templates added to the new group Post Rates templates.
