### ISSUE TITLE
Remove redundant list of users on mouse hover

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#22]
Is it really necessary to show usernames on mouse hover on thread list? Can we save one query?

![image](https://user-images.githubusercontent.com/778890/34421991-0077dc0e-ec13-11e7-8f1d-a79326405752.png)

**Comment by WhiteNeo** [comment]
I think yeah because all systems in the next future will add this and i think users will ask for it so is only one query, any other system have it like mention me on user list load, but there are a plenty of queries like user search the same happens multiqueries with lesser information so it was not a posible high load but light and usefull. Because lists all thread contents and you may see what users and date has rated the posts inside that thread and when click it you may see which posts and more, so it is an active and usefull thread or not for me that is the right direction.

In the first writen version i have seen only marks the first post but i think this way save many queries because in any other systems this require a query for every listed thread, so it takes 10 if you list 10 thread by page or more. This wont take none query. So it saves that query even in posts to renderize and optimize this plugin and only a light load for one query for every mouseover item if you reload it no problem, no queries are there only is one per time :) i have taken care of any part of this plugin so the best way and option is this, and only lists the latest 10 or whatever you have setting it up into plugin settings and full list is on click.

Customizations and more maybe it is taken but i dunno. I will work on some issues but this is the right way i think because all users ask for preview some information before enter some thread, so this way when they see actions one way or anothers takes their attention and will enter to the thread :)
