### ISSUE TITLE
Add cursor: pointer for emoji icons in member profile (links) + post

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#37]
![image](https://user-images.githubusercontent.com/778890/34578404-1c7a287c-f185-11e7-95dc-fc3fa285aa80.png)

 Moreover one more in posts ->
![image](https://user-images.githubusercontent.com/778890/34578744-65dd991c-f186-11e7-9089-a6b62845e7ba.png)

**Comment by WhiteNeo** [comment]
Yes i will add on clickable links it is easy to do with css class so i wil fix this soon. Thanks again for your time.

**Comment by Eldenroot** [comment]
You are welcome. I wanted to send you a PR with code changes but it is easier to report it here... it is too difficult to follow all your changes on GitHub

**Comment by WhiteNeo** [comment]
At this moment i will not change other things unleas an important bugs are appeared. Everytime i upload changes due my pc is broken and sometimes lightdowns shutoff and all progress would be missed, so i try to upload all posible changes i make anytime i can to not loose data as many other times in the past. Because some codes are loosed due this and the file is damaged or parts are changed so i try to not make it confusing for me at this point :)

But now before start writing new code lines i dowload the current github files, and set into my localhost location. But it is for now that i have no pc with a no break :)

You can see this in first progress when i can write and upload final tested progress with my broken laptop :) now i am on a desktop and it is hard to work with this pc.

**Comment by Eldenroot** [comment]
It is fine mate :) I would like to help you make this plugin perfect :)

Now focus on stabilising code and fixing bugs, then you can add more features.

**Comment by WhiteNeo** [comment]
Yes i am writing in settings new posible options to not disable and enable again, only upload new file of plugin and that have to be the trick :).

**Comment by Eldenroot** [comment]
@WhiteNeo - last issue with this:
- remove cursor: pointer here - when you mouse hover on emoji name, is it needed there? Maybe it should be without pointer (no link, so it seems to be redundant)
![image](https://user-images.githubusercontent.com/778890/34649272-11127664-f3ac-11e7-939b-c7f9beba2086.png)

**Comment by WhiteNeo** [comment]
Ok this is done, i have assinged to you, but i am writting now the missing code parts, so it is done with a new style addition.
