### ISSUE TITLE
Add new settings - allow only adding, not removing rates

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#39]
As title says, for some admins could be really useful in future.

**Comment by WhiteNeo** [comment]
Nope due ajax and first version does it so it will break ajax and causes many other bugs for sure and it will break many other templates. Remove it's an important feature that everyone use actually no one uses only add and if i add this option i have to rewrite all entire code again but yes i will add this option in a future release but not now :)

**Comment by Eldenroot** [comment]
OK, it is fine, just lave this ticket open for easier tracking in future :)

**Comment by Eldenroot** [comment]
Works fine, just 1 improvement -> show jGrowl notification in the top right corner when user click to the button in postbit (_notice - cursor: pointer is still applied here_). Show in jGrowl notification that removing rates from post is not possible.

**Comment by WhiteNeo** [comment]
Yes that are in there but only if users go to a bypass otherwise only shows the button and not the action, if we show jGrowl and make this as you wish we miss many queries to do this task, so the best way is disable to not provide any queries so will be save more than 3 queries :)

**Comment by WhiteNeo** [comment]
I think this can be marked due this way we have 3 queries at least that is not running, otherwise if we let the users can click and see an error we have to verify that the user have no permissions to remove rates so it takes some queries or redundant data retrieved. I think the best way is the current one. Maybe in jgrowl can provide extra message about this remove or not i do not know :)

**Comment by Eldenroot** [comment]
Should be fine, thank you!

**Comment by Eldenroot** [comment]
OK, I will leave open: it sound useful:

> Maybe in jgrowl can provide extra message about this remove or not i do not know :)

**Comment by WhiteNeo** [comment]
Yes i am working on this right now, the next are other issues.

**Comment by WhiteNeo** [comment]
This is done, but now i have to test this part to make sure it is working fine, due i have added the message in jGrowl to let user know when add an emoji, and if click on remove if you have no permission a new jGrowl, otherwise, jGrowl and reaction removes success.

This part is one of the most importants due i have to add js routines, lang vars and more and make sure all is working fine i will review this right now.
