### ISSUE TITLE
Highlight feature - improvements

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#40]
I cannot reopen my issues closed by you, so I am opening the new ticket.

#30 
 
Also, is possible to add ajax for this feature? I mean to add green color without refreshing the page (I am just asking, I am not sure if it is server performance friendly or not).

**Comment by WhiteNeo** [comment]
Yeah i see the point but i have to review it due maybe breaks other styles in that way because mybb uses it.

So i add this class to only post message content not to all entire post due other class to mark, closed, modertion tools, etc uses it and this way all must be break but i will se what can i do

**Comment by Eldenroot** [comment]
I will reopen this issue for easier tracking. You can make {$dnt_prt_hl_class} working in postbit and postbit classic template, so asmins can adjust templates :)

**Comment by Eldenroot** [comment]
OK, there are two ways:
1) you can see select/delete/mark whatever for moderators -> just add this css stuff into .post_content, there is an output:
![image](https://user-images.githubusercontent.com/778890/34619520-b13b57a2-f242-11e7-9cf6-7b11394ac707.png)

2) change color for the whole post, you wont see different color for selected/deleted/marked post in mod tools, there is an output
![image](https://user-images.githubusercontent.com/778890/34619576-debccba2-f242-11e7-86d3-6ce98a9b7f2d.png)

**Comment by WhiteNeo** [comment]
Yeah i see second one brokes all, so no that is not factible, because it breaks all css of mybb, so i have added into post content is the best way, because that way all works fine and that is the right way to do it, because many users and me use this tools and if is visually marked then we go to that post otherwise will be ignore all posts in that marks, so yeah the best way for all.

**Comment by Eldenroot** [comment]
Nice, works fine, thx!
