### ISSUE TITLE
Issues with double titles on mouse hover

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#42]
We have a serious issue with doubling "title" tags for emoji images. When you disable displaying user list on mouse hover, there are two titles displayed - one comes from "title" tag in img and the second one from javascript

**Comment by WhiteNeo** [comment]
What part ?

Because button of reactions do not work that place but i have to fix this as a first priority task thanks again @Eldenroot

**Comment by Eldenroot** [comment]
You have to set this to "0"
![image](https://user-images.githubusercontent.com/778890/34618908-95ea2ef8-f240-11e7-9433-0f8b663ccd44.png)

Then go to post with rating received and hover on any emoji reaction.

**Comment by WhiteNeo** [comment]
I have tested some times but i am unable to reproduce this, i set it to 0 and leave blank and only one instance is taken, by the way there have not see twice due i do not add nothing there, only in new rate button for reactions in gif, but nothing else, i have changed style customizations to standarize for chrome and mozilla, and allways i use mozilla due is not invasive as chrome who allways is executing since os load and consume many unnecesary recourses of the pc. I use mozilla because have many developer tools that i have used some time and for me is the best way to develop and debug.

Anyway i will test it on chrome but it is weird, what other settings are changed in your side ?

I mean changed compared with default ones :)

I will catch this anyway to fix it asap.

**Comment by Eldenroot** [comment]
Tested in Firefox and in Google Chrome - same output in both browsers.

![img_20180105_183255](https://user-images.githubusercontent.com/778890/34621140-48293df0-f248-11e7-8a90-700dbfdcbab9.jpg)

**Comment by WhiteNeo** [comment]
Ok that is title tags in all browsers so we have to remove all then :)

Or change some parts due all title tags are tooltips by explorers since 1995 with iexplorer 3, and keeps it on :)

I will fix this is easy to do :)

**Comment by Eldenroot** [comment]
OK but then you wont see the name for the reaction when you will use list of users on mouse hover enabled... Is possible to combine them together, something like Facebook does?

**Comment by Eldenroot** [comment]
Something like this:
![image](https://user-images.githubusercontent.com/778890/34622192-7eba14ee-f24c-11e7-99a1-61a97656100e.png)

Name of reaction is bold above the list of users and there is a counter at the end of the displayed users - and X more...

**Comment by WhiteNeo** [comment]
Yes that is ready :) is what i am working on exactly that parts but i will upload when are ready :)

**Comment by WhiteNeo** [comment]
Ok this is done :) Test it and let me know...
