### ISSUE TITLE
Please revert latest changes - a lot of things is not working :(

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#46]
Version from 5.1.2018 is fine, almost bug free... but everything from 6.1.2018 is bugged as hell. For me, nothing is working - ajax for adding/removing posts; emojis in threadlist; etc.

I will try to catch all new bugs but it will take some time :(

**Comment by WhiteNeo** [comment]
Yeah because this new version removes masive queries that are around. So i have added new fields in database. But i have no time to finish yet. Only fresh installs must work. But when i have some time it must be done :) it is working fine but only fresh install. Make a backup of plugin table install loosing all data then restore that table and must work.

**Comment by WhiteNeo** [comment]
I have added some changes in this last one to fix and add all other issues you have asked for, all have to works fine, i think many of your "new improvements, sugestions are taken in mind", so i have removed many parts of unnecesary code, this time is the best and working on version i have tested in local, i have not updated yet into my website, because it need some template additions, style addittions, table additions and more, that is why you have experienced errors in this version, because you need to run update task to get the necesary data, js are changed too, so you must clear cache and reload to load new js instances of code.

**Comment by Eldenroot** [comment]
All should be fine, thank you!
