### ISSUE TITLE
Simple Like importer is broken.

### ISSUE THREAD

**Issue by insert-mx** [WhiteNeo/post_rate#52]
Import from Simple Likes plugin is broken.
Por ejemplo
else if($db->table_exists("post_likes") && $db->table_exists('thx'))  debería ser:

else if($db->table_exists("post_likes") && $db->table_exists('dnt_post_rate')).

**Comment by WhiteNeo** [comment]
I need that plugin or a db with data from that plugin anyway to rest it only i have tested with thanks system so i think i have some typo errors but thankd for the comment and when an issue was solved let me know to close that issue and go to work with the  next one please. I am working in other issues at this moment but i will review all systems rep of mybb would be added either

**Comment by WhiteNeo** [comment]
Ok give it a try and let m eknow if data was fine, because this maybe have some issues yet so i have to test more,i have only testes with thanks and thanyoumybb system from mybb and all works fine i have to test with simple likes, thankyou like and mybb reputation system (this one is the last addittion i willmake maybe, but not for sure i will focus my attention in other two who are missing at this point).

**Comment by insert-mx** [comment]
Date error in new version
![dates](https://user-images.githubusercontent.com/21194526/34764601-a7373be8-f5b4-11e7-8548-03443dbddc9c.jpg)
Post_Likes table
![postlike](https://user-images.githubusercontent.com/21194526/34764757-202ac290-f5b5-11e7-98a9-51cb65619d9c.jpg)

In my forum (698k post) is too slow to install and recount post rates  (109k simple likes).

**Comment by WhiteNeo** [comment]
it is because the first simple likes have no date rows, the lates version i
have dowloaded from the mods site have the new date field so i have taken
that field. But all plugins uses unix datestamp. and from provided image is
not formated date and this value as timestam would be broke due that mod.

i need some examples to try change that date formats into unix mybb default
timestamps to fix it.

but i need at least a database with installed simple likes with data
recorded to work and test. See what is happen now inside rows and analize
this situation to write right lines for converter to rewrite all dates to
the right timestamps.

**Comment by insert-mx** [comment]
I have exported some data form post_likes table

File removed thanks....

**Comment by WhiteNeo** [comment]
Yes tha is the same as the image you have provided i need real data a
database with entire data to retrieve information, then analize it, convert
and compare results, to make the best and functional code for it, in this
way i have to analize if i have the time to add this mod, add many data as
i can but a real data to work with. Sorry but the provided file is the same
as image do not serve for anything to me. Due this is your data, my posts
table, users are not too much as you so results will never can be added
into database, and if i change data well i think best way is install that
mod, make some likes in a real fictional database, anyone can do that, a
new database, with real data about this, and i can compare and analize that
way. So i will do it when i have some free time to do, but first i will fix
all issues to put my hands in this :)

Anyway thanks for your time.

2018-01-11 2:02 GMT-06:00 insert-mx <notifications@github.com>:

**Comment by WhiteNeo** [comment]
Ok bro i have tested in my db with some data retrieved and it works fine. (with the latest changed i make of course, now it adds mybb reputation system and simple likes old and new versions tested and working successfull.

So now download actual files, and run the converter.php actual file, once the process have finished you will see all data, if you have runed the converter then recount is not needed unleass you have new data (likes). But you can import actual likes then configure your plugin at own needs and finally run the recount tool. Now all your data must be fine :)

See yah and thanks for your contribution.


https://mega.nz/#!X4A0xbyB!AI3gVYg_UR0-wqtB-lySp009gpaVF9S6hWAd_U0jbNI
