### ISSUE TITLE
Different css class for "div" in post and "div" in member profile

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#55]
It will allow easier styling :)

**Comment by Eldenroot** [comment]
It is needed, because same template is used in member profile and in post. We need 2 different templates for easier customization, right now I cannot apply own style for post and different style for member profile :(

![image](https://user-images.githubusercontent.com/778890/34693019-73c47e58-f4c2-11e7-8f6d-4749e98cbf61.png)

**Comment by WhiteNeo** [comment]
Yes i will add a new class for posts and member parts that way you can edit at own prefs :). I think it will be easy to code and perform :)

**Comment by WhiteNeo** [comment]
Or more easy i can create a new template for member profile and load it there but i have to review if needs only one or two or a class addition only :)

**Comment by WhiteNeo** [comment]
Ok this is done, let me know i have added new template on member profile only one is needed and do not take ajax, so it have to works fine this way :)

**Comment by Eldenroot** [comment]
@WhiteNeo - thank you, I will try on Friday, I am not at home.

**Comment by WhiteNeo** [comment]
This is done so i let in your hands the latest tests to close this issue.

I have worked on some other parts of the plugin and code review so i think this is the latest working on version of this plugin. i can not change icon order due many users already uses it at least 10 as far as i know and mee too, so i can not change it that order, but you can change it to whatever you like inside all templates, there you can see ordered items in order to appear. You have to change all items in templates at your own :)

If nobody have it in use i can change it to whatever but right now many are using it and there are no problem with icon order, because is not the same as fb, due copyrights, at least an approuch, but many parts i have tryed to make and write different ways in code or i dunno i have no source code of fb.

But at this point is too hard to change that without affecting all people who use already as me and others :)

**Comment by Eldenroot** [comment]
OK, so what do I need to change? Just img src and lang variable?

**Comment by WhiteNeo** [comment]
Only images inside templates order, nothing else.
