### ISSUE TITLE
PHP error when I wanna user converter

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#59]
![image](https://user-images.githubusercontent.com/778890/34826979-f485de66-f6d8-11e7-8f33-9ff52c2e4c14.png)

It is displayed when I wanna run converter.php :(

**Comment by Eldenroot** [comment]
OK, it is because I ran this converter from /extras/converter.php, now works fine, maybe you should add more info for others.

**Comment by WhiteNeo** [comment]
information is added on readme maybe you didn't see it but it was clear
because many users have used reading that information. extras folders are
allways for extras like html instructions and more. it is like users who
upload upload dir into ftp. it sais upload so you have to upload it and if
doc is readed you should know :)
