### ISSUE TITLE
Issues after converting from Thank you/like system

### ISSUE THREAD

**Issue by Eldenroot** [WhiteNeo/post_rate#61]
There are some issues for all rates converted from Thank You/Like system

- these rates are not shown on mouse hover (emoji) - only number of rates is shown, on mouse hover only name of emoji is displayed...
- these rates are not shown in rates given/received search page (anyway they are counted right, you can see the total number of given/received but when you click on it -> no data error)
- these rates are not shown in threadlist

Only new added rates (not converted) are displayed correctly. Is possible to fix this issue somehow? Thank you!

**Comment by WhiteNeo** [comment]
Yes i was waiting to review it, i see that was for the SQL provided have not thread value is right before so we have to verify again bro but you leave me alone waitnig, hahaha.

Well let me know to review it again with the converter to fix it asap.

Let me know then to gotcha it and fix this i think i was write some code that must work, but not for sure :) And we have to review entries into database and some other stuff :)

**Comment by Eldenroot** [comment]
@WhiteNeo - I am sorry, I had some issues with templates etc. 

For now, these 3 issues are the only one which I have found.

**Comment by WhiteNeo** [comment]
Thanks for the comments i will review it with the provided data because you have many changes into database like innoDB, php 64mb utf8 i am working with utf8 but normal instances and SQLimproved. Because is less problematic than innoDB, but innoDB is the best db motor, so i will review it all this stuff again :)

For now i can tell converter have missing data so all data are wrong for that reason and we have to run again converter and rebuild tasks but when a right file to retrieve all data, because tlid is the id of current tyl, not thread id, we need thread id, so it searchs for thread ids that does not exist. In the latest recount task we run success and the first and only one that retrieve matches :)

**Comment by Eldenroot** [comment]
Yes, thats the issue - pm sent :)

**Comment by WhiteNeo** [comment]
Ok this one have retrieved due converter error, now you can upload every converter of any case and do the run task, doc will be updated now.
